version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      # DATABASE_URL should be set in .env file or passed through environment
    volumes:
      - .:/app
    command: gunicorn --config gunicorn.conf.py app:app
