"""Create hydration_logs table

Revision ID: 00d64fb112a4
Revises: e7491ee313ad
Create Date: 2025-04-07 19:07:59.424392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00d64fb112a4'
down_revision = 'e7491ee313ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydration_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_sk', sa.Integer(), nullable=False),
    sa.Column('water_intake', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_sk'], ['users.user_sk'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hydration_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydration_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_sk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_sk'], ['users.user_sk'], name='hydration_log_user_sk_fkey'),
    sa.PrimaryKeyConstraint('id', name='hydration_log_pkey')
    )
    op.drop_table('hydration_logs')
    # ### end Alembic commands ###
