"""Initial schema

Revision ID: e7491ee313ad
Revises: 
Create Date: 2025-04-07 18:52:49.101914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7491ee313ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydration_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_sk', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_sk'], ['users.user_sk'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hydration_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydration_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_sk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('water_intake', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_sk'], ['users.user_sk'], name='hydration_logs_user_sk_fkey'),
    sa.PrimaryKeyConstraint('id', name='hydration_logs_pkey')
    )
    op.drop_table('hydration_log')
    # ### end Alembic commands ###
